# Generated by Django 3.0.7 on 2022-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, default='media/j1.jpg', null=True, upload_to='media/'),
        ),
    ]
