# Generated by Django 3.0.7 on 2022-01-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220127_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_Number', models.CharField(max_length=15)),
                ('write', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
