# Generated by Django 3.0.7 on 2022-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_comment_user_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='media/j1.jpg', null=True, upload_to='media/'),
        ),
    ]
